-- MySQL Script generated by MySQL Workbench
-- Mon Dec 18 14:06:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `idTask` INT NOT NULL,
  `idCollectionAgent` VARCHAR(45) NULL,
  `Date` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`idTask`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Collection_Agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Collection_Agent` (
  `idCollection_Agent` INT NOT NULL,
  `Area` VARCHAR(45) NULL,
  `idTask` VARCHAR(45) NULL,
  `Task_idTask` INT NOT NULL,
  PRIMARY KEY (`idCollection_Agent`),
  INDEX `fk_Collection_Agent_Task1_idx` (`Task_idTask` ASC),
  CONSTRAINT `fk_Collection_Agent_Task1`
    FOREIGN KEY (`Task_idTask`)
    REFERENCES `mydb`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `idPerson` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Collection_Agent_idCollection_Agent` INT NOT NULL,
  PRIMARY KEY (`idPerson`),
  INDEX `fk_Person_Collection_Agent1_idx` (`Collection_Agent_idCollection_Agent` ASC),
  CONSTRAINT `fk_Person_Collection_Agent1`
    FOREIGN KEY (`Collection_Agent_idCollection_Agent`)
    REFERENCES `mydb`.`Collection_Agent` (`idCollection_Agent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Waste_producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Waste_producer` (
  `idWaste_producer` INT NOT NULL,
  `GPS_Latitude` VARCHAR(45) NULL,
  `GPS_Longitude` VARCHAR(45) NULL,
  `QR_Code` VARCHAR(45) NULL,
  `idLocation` VARCHAR(45) NULL,
  `Person_idPerson` INT NOT NULL,
  PRIMARY KEY (`idWaste_producer`),
  INDEX `fk_Waste_producer_Person1_idx` (`Person_idPerson` ASC),
  CONSTRAINT `fk_Waste_producer_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location_Type` (
  `idLocation_Type` INT NOT NULL,
  `Location_Name` VARCHAR(45) NULL,
  `Waste_producer_idWaste_producer` INT NOT NULL,
  PRIMARY KEY (`idLocation_Type`, `Waste_producer_idWaste_producer`),
  INDEX `fk_Location_Type_Waste_producer1_idx` (`Waste_producer_idWaste_producer` ASC),
  CONSTRAINT `fk_Location_Type_Waste_producer1`
    FOREIGN KEY (`Waste_producer_idWaste_producer`)
    REFERENCES `mydb`.`Waste_producer` (`idWaste_producer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task_Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task_Location` (
  `idTask_Location` INT NOT NULL,
  `idWaste_Producer` VARCHAR(45) NULL,
  `Task_idTask` INT NOT NULL,
  PRIMARY KEY (`idTask_Location`),
  INDEX `fk_Task_Location_Task1_idx` (`Task_idTask` ASC),
  CONSTRAINT `fk_Task_Location_Task1`
    FOREIGN KEY (`Task_idTask`)
    REFERENCES `mydb`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
